-- ============================================================
-- NexaBank Complete Schema  (DROP & RECREATE safe)
-- ============================================================
CREATE DATABASE IF NOT EXISTS bank_db;
USE bank_db;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS EMPLOYEE_SUPERVISES_CUSTOMER;
DROP TABLE IF EXISTS AUDIT_LOG_ENTRY;
DROP TABLE IF EXISTS LOAN_TERM_DETAIL;
DROP TABLE IF EXISTS LOAN_REQUEST;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS TRANSACTION;
DROP TABLE IF EXISTS ACCOUNT_HOLDER;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS BANK_CUSTOMER;
DROP TABLE IF EXISTS BANK_EMPLOYEE;
SET FOREIGN_KEY_CHECKS = 1;

-- BANK_EMPLOYEE
CREATE TABLE BANK_EMPLOYEE (
  EID            INT PRIMARY KEY AUTO_INCREMENT,
  Name           VARCHAR(100),
  LName          VARCHAR(100),
  Salary         DECIMAL(10,2),
  D_und          VARCHAR(100),
  JoinedDate     DATE,
  Responsibility VARCHAR(255),
  BranchID       INT,
  HouseNo        VARCHAR(50),
  City           VARCHAR(100),
  Country        VARCHAR(100),
  Address        TEXT,
  ContactNo      VARCHAR(15),
  PasswordHash   VARCHAR(255)
);

-- BANK_CUSTOMER
CREATE TABLE BANK_CUSTOMER (
  Cust_ID        INT PRIMARY KEY AUTO_INCREMENT,
  FName          VARCHAR(100) NOT NULL,
  LName          VARCHAR(100),
  TaxID          VARCHAR(50),
  ContactNo      VARCHAR(15),
  Address        TEXT,
  DrivingLicence VARCHAR(50),
  CustDOB        DATE,
  CustIDProofType VARCHAR(50) DEFAULT 'AADHAAR',
  CustomerType   ENUM('INDIVIDUAL','CORPORATE','VIP') DEFAULT 'INDIVIDUAL',
  Email          VARCHAR(150),
  PasswordHash   VARCHAR(255)
);

-- ACCOUNT
CREATE TABLE ACCOUNT (
  Account_No   INT PRIMARY KEY AUTO_INCREMENT,
  CustID       INT,
  BranchID     INT,
  AccountType  VARCHAR(50) DEFAULT 'SAVINGS',
  Balance      DECIMAL(15,2) DEFAULT 0.00,
  CreatedAt    DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CustID) REFERENCES BANK_CUSTOMER(Cust_ID) ON DELETE SET NULL
);

-- ACCOUNT_HOLDER
CREATE TABLE ACCOUNT_HOLDER (
  HolderID     INT PRIMARY KEY AUTO_INCREMENT,
  Account_No   INT,
  Cust_ID      INT,
  HolderName   VARCHAR(100),
  HolderType   VARCHAR(50),
  DOB          DATE,
  ContactNo    VARCHAR(15),
  Email        VARCHAR(150),
  Address      TEXT,
  Relationship VARCHAR(50) DEFAULT 'SELF',
  IDProofType  VARCHAR(50) DEFAULT 'AADHAAR',
  FOREIGN KEY (Account_No) REFERENCES ACCOUNT(Account_No) ON DELETE CASCADE,
  FOREIGN KEY (Cust_ID)    REFERENCES BANK_CUSTOMER(Cust_ID) ON DELETE SET NULL
);

-- TRANSACTION
CREATE TABLE TRANSACTION (
  Txn_ID           INT PRIMARY KEY AUTO_INCREMENT,
  Amount           DECIMAL(15,2),
  Transaction_Type ENUM('CREDIT','DEBIT') DEFAULT 'DEBIT',
  Description      VARCHAR(255),
  Transaction_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
  PayMethod        VARCHAR(50),
  CustID           INT,
  Account_No       INT,
  FOREIGN KEY (CustID)      REFERENCES BANK_CUSTOMER(Cust_ID) ON DELETE SET NULL,
  FOREIGN KEY (Account_No)  REFERENCES ACCOUNT(Account_No) ON DELETE SET NULL
);

-- PAYMENT
CREATE TABLE PAYMENT (
  PaymentID   INT PRIMARY KEY AUTO_INCREMENT,
  Txn_ID      INT,
  Amount      DECIMAL(15,2),
  PaymentDate DATE,
  Mode        VARCHAR(50),
  FOREIGN KEY (Txn_ID) REFERENCES TRANSACTION(Txn_ID) ON DELETE CASCADE
);

-- LOAN_REQUEST
CREATE TABLE LOAN_REQUEST (
  LoanID           INT PRIMARY KEY AUTO_INCREMENT,
  Cust_ID          INT,
  Requested_Amount DECIMAL(15,2),
  LoanRate         DECIMAL(5,2),
  TenureMonths     INT,
  ApprovalStatus   ENUM('PENDING','APPROVED','REJECTED') DEFAULT 'PENDING',
  PickupDate       DATE,
  PickupLocation   VARCHAR(255),
  AppcelationDetails TEXT,
  CreatedAt        DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Cust_ID) REFERENCES BANK_CUSTOMER(Cust_ID) ON DELETE CASCADE
);

-- LOAN_TERM_DETAIL
CREATE TABLE LOAN_TERM_DETAIL (
  DetailID           INT PRIMARY KEY AUTO_INCREMENT,
  LoanID             INT,
  noOfDays           INT,
  NewTerms           TEXT,
  CancellationReason TEXT,
  FOREIGN KEY (LoanID) REFERENCES LOAN_REQUEST(LoanID) ON DELETE CASCADE
);

-- AUDIT_LOG_ENTRY
CREATE TABLE AUDIT_LOG_ENTRY (
  LogID        INT PRIMARY KEY AUTO_INCREMENT,
  TxnID        INT,
  DetailID     INT,
  LogType      VARCHAR(50),
  LogTimestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  LogDetails   TEXT,
  FOREIGN KEY (TxnID)     REFERENCES TRANSACTION(Txn_ID) ON DELETE SET NULL,
  FOREIGN KEY (DetailID)  REFERENCES LOAN_TERM_DETAIL(DetailID) ON DELETE SET NULL
);

-- EMPLOYEE_SUPERVISES_CUSTOMER
CREATE TABLE EMPLOYEE_SUPERVISES_CUSTOMER (
  EID      INT,
  Cust_ID  INT,
  PRIMARY KEY (EID, Cust_ID),
  FOREIGN KEY (EID)     REFERENCES BANK_EMPLOYEE(EID) ON DELETE CASCADE,
  FOREIGN KEY (Cust_ID) REFERENCES BANK_CUSTOMER(Cust_ID) ON DELETE CASCADE
);

-- ── Sample Admin Employee (password: admin123) ──────────────
INSERT INTO BANK_EMPLOYEE (Name, LName, Responsibility, PasswordHash)
VALUES ('Admin', 'NexaBank', 'Branch Manager',
  '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi');